# This file configures the latexmk command you can use to compile
# the pdf version of the blueprint
$pdf_mode = 1;
$pdflatex = 'pdflatex -synctex=1 -interaction=batchmode';
@default_files = ('print.tex');
